<a href="https://colab.research.google.com/github/Adil-Aquil-Ahmad/NLP-Lab/blob/main/NLP_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk
import string
import random
import pandas as pd
import numpy as np

resources = ['brown', 'gutenberg', 'punkt', 'punkt_tab', 'stopwords',
             'wordnet', 'omw-1.4', 'words']
for res in resources:
    nltk.download(res, quiet=True)

random.seed(42)
print("Setup complete. All NLTK resources downloaded.")

Setup complete. All NLTK resources downloaded.

In [ ]:
from nltk.corpus import brown, stopwords
from nltk.tokenize import sent_tokenize, word_tokenize

brown_text = ' '.join(brown.words(categories='news')[:2000])

sentences = sent_tokenize(brown_text)[:20]
print(f"Total sentences selected: {len(sentences)}")
print("\nExample sentence:\n", sentences[0])

Total sentences selected: 20

Example sentence:
 The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced `` no evidence '' that any irregularities took place .

In [ ]:
stop_words = set(stopwords.words('english'))
punctuations = set(string.punctuation)

def preprocess_sentence(sentence):
    """Tokenize, lowercase, and remove punctuation + stop words."""
    word_tokens = word_tokenize(sentence)
    lower_tokens = [w.lower() for w in word_tokens]
    cleaned_tokens = [w for w in lower_tokens
                       if w.isalpha() and w not in stop_words]
    return word_tokens, lower_tokens, cleaned_tokens

In [ ]:
results_q1 = []
for i, sent in enumerate(sentences[:5], start=1):
    word_tokens, lower_tokens, cleaned_tokens = preprocess_sentence(sent)
    results_q1.append({
        'Sentence #': i,
        'Original Sentence': sent,
        'Word Tokens': word_tokens,
        'Cleaned Tokens': cleaned_tokens
    })
    print(f"--- Sentence {i} ---")
    print("Original :", sent)
    print("Word Tokens:", word_tokens)
    print("Cleaned Tokens (lowercase, no punctuation/stopwords):", cleaned_tokens)
    print()

df_q1 = pd.DataFrame(results_q1)
df_q1

--- Sentence 1 ---
Original : The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced `` no evidence '' that any irregularities took place .
Word Tokens: ['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', 'Friday', 'an', 'investigation', 'of', 'Atlanta', "'s", 'recent', 'primary', 'election', 'produced', '``', 'no', 'evidence', '``', 'that', 'any', 'irregularities', 'took', 'place', '.']
Cleaned Tokens (lowercase, no punctuation/stopwords): ['fulton', 'county', 'grand', 'jury', 'said', 'friday', 'investigation', 'atlanta', 'recent', 'primary', 'election', 'produced', 'evidence', 'irregularities', 'took', 'place']

--- Sentence 2 ---
Original : The jury further said in term-end presentments that the City Executive Committee , which had over-all charge of the election , `` deserves the praise and thanks of the City of Atlanta '' for the manner in which the election was conducted .
Word Tokens: ['The', 'jury', 'further', 'said', 'in', 'term-end', 'presentments', 'that', 'the', 'City', 'Executive', 'Committee', ',', 'which', 'had', 'over-all', 'charge', 'of', 'the', 'election', ',', '``', 'deserves', 'the', 'praise', 'and', 'thanks', 'of', 'the', 'City', 'of', 'Atlanta', '``', 'for', 'the', 'manner', 'in', 'which', 'the', 'election', 'was', 'conducted', '.']
Cleaned Tokens (lowercase, no punctuation/stopwords): ['jury', 'said', 'presentments', 'city', 'executive', 'committee', 'charge', 'election', 'deserves', 'praise', 'thanks', 'city', 'atlanta', 'manner', 'election', 'conducted']

--- Sentence 3 ---
Original : The September-October term jury had been charged by Fulton Superior Court Judge Durwood Pye to investigate reports of possible `` irregularities '' in the hard-fought primary which was won by Mayor-nominate Ivan Allen Jr. .
Word Tokens: ['The', 'September-October', 'term', 'jury', 'had', 'been', 'charged', 'by', 'Fulton', 'Superior', 'Court', 'Judge', 'Durwood', 'Pye', 'to', 'investigate', 'reports', 'of', 'possible', '``', 'irregularities', '``', 'in', 'the', 'hard-fought', 'primary', 'which', 'was', 'won', 'by', 'Mayor-nominate', 'Ivan', 'Allen', 'Jr.', '.']
Cleaned Tokens (lowercase, no punctuation/stopwords): ['term', 'jury', 'charged', 'fulton', 'superior', 'court', 'judge', 'durwood', 'pye', 'investigate', 'reports', 'possible', 'irregularities', 'primary', 'ivan', 'allen']

--- Sentence 4 ---
Original : `` Only a relative handful of such reports was received '' , the jury said , `` considering the widespread interest in the election , the number of voters and the size of this city '' .
Word Tokens: ['``', 'Only', 'a', 'relative', 'handful', 'of', 'such', 'reports', 'was', 'received', '``', ',', 'the', 'jury', 'said', ',', '``', 'considering', 'the', 'widespread', 'interest', 'in', 'the', 'election', ',', 'the', 'number', 'of', 'voters', 'and', 'the', 'size', 'of', 'this', 'city', '``', '.']
Cleaned Tokens (lowercase, no punctuation/stopwords): ['relative', 'handful', 'reports', 'received', 'jury', 'said', 'considering', 'widespread', 'interest', 'election', 'number', 'voters', 'size', 'city']

--- Sentence 5 ---
Original : The jury said it did find that many of Georgia's registration and election laws `` are outmoded or inadequate and often ambiguous '' .
Word Tokens: ['The', 'jury', 'said', 'it', 'did', 'find', 'that', 'many', 'of', 'Georgia', "'s", 'registration', 'and', 'election', 'laws', '``', 'are', 'outmoded', 'or', 'inadequate', 'and', 'often', 'ambiguous', '``', '.']
Cleaned Tokens (lowercase, no punctuation/stopwords): ['jury', 'said', 'find', 'many', 'georgia', 'registration', 'election', 'laws', 'outmoded', 'inadequate', 'often', 'ambiguous']

,Sentence #,Original Sentence,Word Tokens,Cleaned Tokens
0,1,The Fulton County Grand Jury said Friday an in...,"[The, Fulton, County, Grand, Jury, said, Frida...","[fulton, county, grand, jury, said, friday, in..."
1,2,The jury further said in term-end presentments...,"[The, jury, further, said, in, term-end, prese...","[jury, said, presentments, city, executive, co..."
2,3,The September-October term jury had been charg...,"[The, September-October, term, jury, had, been...","[term, jury, charged, fulton, superior, court,..."
3,4,`` Only a relative handful of such reports was...,"[``, Only, a, relative, handful, of, such, rep...","[relative, handful, reports, received, jury, s..."
4,5,The jury said it did find that many of Georgia...,"[The, jury, said, it, did, find, that, many, o...","[jury, said, find, many, georgia, registration..."

In [ ]:
from nltk.stem import PorterStemmer, WordNetLemmatizer

all_alpha_words = [w.lower() for w in brown.words(categories='news')
                    if w.isalpha() and w.lower() not in stop_words and len(w) > 2]

seen = set()
unique_words = []
for w in all_alpha_words:
    if w not in seen:
        seen.add(w)
        unique_words.append(w)

sample_words = unique_words[:30]

required_words = ['playing', 'studies', 'running', 'better', 'cars']
for w in required_words:
    if w not in sample_words:
        sample_words.append(w)

print(f"Total words selected: {len(sample_words)}")
print(sample_words)

Total words selected: 35
['fulton', 'county', 'grand', 'jury', 'said', 'friday', 'investigation', 'recent', 'primary', 'election', 'produced', 'evidence', 'irregularities', 'took', 'place', 'presentments', 'city', 'executive', 'committee', 'charge', 'deserves', 'praise', 'thanks', 'atlanta', 'manner', 'conducted', 'term', 'charged', 'superior', 'court', 'playing', 'studies', 'running', 'better', 'cars']

In [ ]:
ps = PorterStemmer()
stemmed_words = [ps.stem(w) for w in sample_words]

lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(w, pos='v') for w in sample_words]

df_q2 = pd.DataFrame({
    'Original': sample_words,
    'Stemmed': stemmed_words,
    'Lemmatized': lemmatized_words
})
df_q2

          Original    Stemmed      Lemmatized
0           fulton     fulton          fulton
1           county     counti          county
2            grand      grand           grand
3             jury       juri            jury
4             said       said             say
5           friday     friday          friday
6    investigation   investig   investigation
7           recent     recent          recent
8          primary    primari         primary
9         election      elect        election
10        produced     produc         produce
11        evidence       evid        evidence
12  irregularities  irregular  irregularities
13            took       took            take
14           place      place           place
15    presentments    present    presentments
16            city       citi            city
17       executive     execut       executive
18       committee   committe       committee
19          charge      charg          charge
20        deserves     deserv         deserve
21          praise      prais          praise
22          thanks      thank           thank
23         atlanta    atlanta         atlanta
24          manner     manner          manner
25       conducted    conduct         conduct
26            term       term            term
27         charged      charg          charge
28        superior   superior        superior
29           court      court           court
30         playing       play            play
31         studies      studi           study
32         running        run             run
33          better     better          better
34            cars        car            cars

In [ ]:
df_q2[df_q2['Original'].isin(required_words)]

   Original Stemmed Lemmatized
30  playing    play       play
31  studies   studi      study
32  running     run        run
33   better  better     better
34     cars     car       cars

In [ ]:
from nltk.corpus import words as words_corpus

vocabulary = set(w.lower() for w in words_corpus.words())
print(f"Vocabulary size: {len(vocabulary)}")

misspelled_words = ['recieve', 'definately', 'seperate', 'occured', 'adress',
                     'wich', 'beleive', 'goverment', 'tommorow', 'freind']
print("Misspelled words:", misspelled_words)

Vocabulary size: 234377
Misspelled words: ['recieve', 'definately', 'seperate', 'occured', 'adress', 'wich', 'beleive', 'goverment', 'tommorow', 'freind']

In [ ]:
def correct_word(word, vocab, max_candidates=200):
    """Return the closest vocabulary word using Levenshtein (edit) distance.
    Narrows the search space first (by first letter and similar length) for speed."""
    word = word.lower()
    if word in vocab:
        return word, 0

    candidates = [w for w in vocab
                  if w and w[0] == word[0] and abs(len(w) - len(word)) <= 2]
    if not candidates:
        candidates = list(vocab)

    best_word, best_dist = None, float('inf')
    for w in candidates:
        d = nltk.edit_distance(word, w)
        if d < best_dist:
            best_word, best_dist = w, d
    return best_word, best_dist

correction_results = []
for mw in misspelled_words:
    correction, dist = correct_word(mw, vocabulary)
    correction_results.append({'Misspelled': mw, 'Suggested Correction': correction, 'Edit Distance': dist})

df_q3 = pd.DataFrame(correction_results)
df_q3

   Misspelled Suggested Correction  Edit Distance
0     recieve              relieve              1
1  definately           definitely              1
2    seperate              sperate              1
3     occured                occur              2
4      adress               adless              1
5        wich                 with              1
6     beleive              beleave              1
7   goverment           government              1
8    tommorow             tomorrow              2
9      freind               friend              2

In [ ]:
example_sentences = [
    "I would like to recieve the package tommorow.",
    "Please definately seperate the two documents.",
    "The goverment occured a major policy change.",
    "This is the correct adress for my freind.",
    "I beleive wich option is best for the project."
]

def correct_sentence(sentence):
    tokens = word_tokenize(sentence)
    corrected_tokens = []
    for t in tokens:
        if t.isalpha() and t.lower() not in vocabulary:
            corrected, _ = correct_word(t, vocabulary)
            corrected_tokens.append(corrected.capitalize() if t[0].isupper() else corrected)
        else:
            corrected_tokens.append(t)
    return ' '.join(corrected_tokens)

for sent in example_sentences:
    corrected = correct_sentence(sent)
    print("Original : ", sent)
    print("Corrected : ", corrected)
    print()

Original :  I would like to recieve the package tommorow.
Corrected :  I would like to relieve the package tomorrow .

Original :  Please definately seperate the two documents.
Corrected :  Please definitely sperate the two document .

Original :  The goverment occured a major policy change.
Corrected :  The government occur a major policy change .

Original :  This is the correct adress for my freind.
Corrected :  This is the correct adless for my friend .

Original :  I beleive wich option is best for the project.
Corrected :  I beleave with option is best for the project .

In [ ]:
from nltk.util import ngrams
from nltk import FreqDist

raw_tokens = brown.words(categories='news')[:10000]

clean_corpus_tokens = [w.lower() for w in raw_tokens if w.isalpha()]
print(f"Total tokens after cleaning: {len(clean_corpus_tokens)}")
print("Sample tokens:", clean_corpus_tokens[:20])

Total tokens after cleaning: 8555
Sample tokens: ['the', 'fulton', 'county', 'grand', 'jury', 'said', 'friday', 'an', 'investigation', 'of', 'recent', 'primary', 'election', 'produced', 'no', 'evidence', 'that', 'any', 'irregularities', 'took']

In [ ]:
unigrams = list(ngrams(clean_corpus_tokens, 1))
bigrams  = list(ngrams(clean_corpus_tokens, 2))
trigrams = list(ngrams(clean_corpus_tokens, 3))

print(f"Number of unigrams: {len(unigrams)}")
print(f"Number of bigrams : {len(bigrams)}")
print(f"Number of trigrams: {len(trigrams)}")

Number of unigrams: 8555
Number of bigrams : 8554
Number of trigrams: 8553

In [ ]:
unigram_freq = FreqDist(unigrams)
bigram_freq  = FreqDist(bigrams)
trigram_freq = FreqDist(trigrams)

top_unigrams = unigram_freq.most_common(10)
top_bigrams  = bigram_freq.most_common(10)
top_trigrams = trigram_freq.most_common(10)

print("Top 10 Unigrams:")
for gram, freq in top_unigrams:
    print(f"  {' '.join(gram):20s} -> {freq}")

print("\nTop 10 Bigrams:")
for gram, freq in top_bigrams:
    print(f"  {' '.join(gram):20s} -> {freq}")

print("\nTop 10 Trigrams:")
for gram, freq in top_trigrams:
    print(f"  {' '.join(gram):25s} -> {freq}")

Top 10 Unigrams:
  the                  -> 675
  of                   -> 315
  to                   -> 265
  a                    -> 207
  in                   -> 195
  and                  -> 174
  for                  -> 110
  that                 -> 99
  would                -> 80
  said                 -> 76

Top 10 Bigrams:
  of the               -> 95
  in the               -> 66
  to the               -> 34
  that the             -> 23
  on the               -> 23
  for the              -> 22
  would be             -> 22
  the state            -> 18
  has been             -> 18
  he said              -> 16

Top 10 Trigrams:
  the united states         -> 12
  the jury said             -> 7
  of the ward               -> 6
  one of the                -> 5
  medical and dental        -> 5
  the president said        -> 5
  that the united           -> 5
  the secretary of          -> 5
  the grand jury            -> 4
  to make the               -> 4

In [ ]:
df_unigrams = pd.DataFrame([(' '.join(g), f) for g, f in top_unigrams], columns=['Unigram', 'Frequency'])
df_bigrams  = pd.DataFrame([(' '.join(g), f) for g, f in top_bigrams],  columns=['Bigram', 'Frequency'])
df_trigrams = pd.DataFrame([(' '.join(g), f) for g, f in top_trigrams], columns=['Trigram', 'Frequency'])

print("Unigram Frequency Table")
display(df_unigrams)
print("\nBigram Frequency Table")
display(df_bigrams)
print("\nTrigram Frequency Table")
display(df_trigrams)

Unigram Frequency Table

  Unigram  Frequency
0     the        675
1      of        315
2      to        265
3       a        207
4      in        195
5     and        174
6     for        110
7    that         99
8   would         80
9    said         76

Bigram Frequency Table

      Bigram  Frequency
0     of the         95
1     in the         66
2     to the         34
3   that the         23
4     on the         23
5    for the         22
6   would be         22
7  the state         18
8   has been         18
9    he said         16

Trigram Frequency Table

              Trigram  Frequency
0   the united states         12
1       the jury said          7
2         of the ward          6
3          one of the          5
4  medical and dental          5
5  the president said          5
6     that the united          5
7    the secretary of          5
8      the grand jury          4
9         to make the          4